### ISSUE TITLE
Incorrect Development Setup Instructions

### ISSUE THREAD

**Issue by Pranav4399** [BeeeQueue/dota-matches-api#188]
Hello. This thread is more of a discussion than an issue. Since I couldn't find the discussion option for the repo, I'm adding it here. I'm currently working on a project to create something similar to [this](https://plaintextsports.com/) but for Dota and your API has been of huge help. 

I just wanted to check with you if there are plans for adding more endpoints and if external contributions are allowed.

Also, I set up the code base in my local, and after running pnpm dev, I'm not sure about the URL that I should access to reach the /v1/matches endpoint locally. I believe it's something to do with Cloudflare credentials. Please do let me know how to setup the development environment locally for the repo and I'd be glad to make my contribution as well. Thanks.

**Comment by BeeeQueue** [comment]
I do not plan to add anything more to this API. 

Local development is currently broken because of upstream issues and we have to wait for them to be fixed in future releases.

I will improve the set up documentation when local development is fixed again.
