### ISSUE TITLE
Nothing returned from https://dota.haglund.dev/v1/matches 

### ISSUE THREAD

**Issue by mhmdaliab** [beeequeue/dota-matches-api#323]
Hey Guys!

Thanks to you incredible effort for such an incredible API. I think I have some problems using them to test it or maybe its an issue. I tried GET method to https://dota.haglund.dev/v1/matches as you mentioned in description and nothing returned but this:

```json
[
  {
    "hash": "f6dc_AhF",
    "matchType": "Bo3",
    "streamUrl": null,
    "startsAt": "2024-09-09T07:00:00.000Z",
    "leagueName": "IESF Central Asia Qualifier 2024",
    "leagueUrl": "https://liquipedia.net/dota2/IESF_World_Championship/2024/Asia/Central",
    "teams": [
      {
        "name": "Uzbekistan",
        "url": "https://liquipedia.net/dota2/index.php?title=Uzbekistan&action=edit&redlink=1"
      },
      {
        "name": "Kyrgyzstan",
        "url": "https://liquipedia.net/dota2/Kyrgyzstan"
      }
    ]
  }
]
```

Could you plz help me for that? I would really appreciate it.

**Comment by beeequeue** [comment]
Liquipedia updated their pages and I haven't had time to update the scraper

**Comment by mhmdaliab** [comment]
Thanks for you quick answer!
Do you have any plans to change the code to make it more reliable in case of these changes?

**Comment by beeequeue** [comment]
At some point, hopefully soon

**Comment by mhmdaliab** [comment]
Thank you very much <3
